name = "docker"
account_id = "b7933b7daf3bfa16780809cfeced63d1"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "you kv id" }
]
